{
 "title": "Host Overview",
 "tags": [ "swift" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-redis-datasource" },
   { "name": "host", "query": "label_values(hostname)" },
   { "name": "instance", "query": "label_values(swift_db_name)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel.all.load{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.free{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "mem.util.cached{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "mem.physmem{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Per-CPU busy (User)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kernel.percpu.cpu.user{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Per-CPU busy (Sys)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kernel.percpu.cpu.sys{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Context switches per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kernel.all.pswitch{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Runnable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel.all.runnable{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.used{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.cached{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.free{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Page fault rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mem.vmstat.pgfault{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Hard fault rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mem.vmstat.pgmajfault{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Network Throughput (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Throughput (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Drops (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.drops{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Drops (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.drops{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Packets (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.packets{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Packets (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.packets{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "TCP Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network.tcp.timeouts{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "TCP Listen Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.listendrops{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.listenoverflows{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.retranssegs{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.fastretrans{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.slowstartretrans{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.synretrans{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read_rawactive{hostname == \"$host\"}",
     "legendFormat": "read $instance"
    },
    {
     "expr": "disk.dev.write_rawactive{hostname == \"$host\"}",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read{hostname == \"$host\"}",
     "legendFormat": "read $instance"
    },
    {
     "expr": "disk.dev.write{hostname == \"$host\"}",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "KiBs" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read_bytes{hostname == \"$host\"}",
     "legendFormat": "read $instance"
    },
    {
     "expr": "disk.dev.write_bytes{hostname == \"$host\"}",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "disk.dev.avactive{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "XFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Number of Inode Attribute Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_attrchg{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Number of Inode Operation Attempt",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_attempts{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Number of Missed Inode Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_missed{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Number of Inodes Found",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_found{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Number of Inode Duplicates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 13, "y": 105 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_dup{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Number of Inode Recycles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_frecycle{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Number of Inode Reclaims",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.inode_ops.ig_reclaims{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "XFS Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "XFS Extent Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.allocs.alloc_extent{hostname == \"$host\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "xfs.perdev.allocs.free_extent{hostname == \"$host\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "XFS Block Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.allocs.alloc_block{hostname == \"$host\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "xfs.perdev.allocs.free_block{hostname == \"$host\"}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "XFS Allocation B-Tree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Allocation B-Tree Lookups/Comparisons",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.alloc_btree.lookup{hostname == \"$host\"}",
     "legendFormat": "lookup"
    },
    {
     "expr": "xfs.perdev.alloc_btree.compare{hostname == \"$host\"}",
     "legendFormat": "compare"
    }
   ]
  },
  {
   "title": "Allocation B-Tree Record Ins/Del",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.alloc_btree.insrec{hostname == \"$host\"}",
     "legendFormat": "insert"
    },
    {
     "expr": "xfs.perdev.alloc_btree.delrec{hostname == \"$host\"}",
     "legendFormat": "delete"
    }
   ]
  },
  { "title": "XFS Inode Flushing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Inode Flushes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.iflush_count{hostname == \"$host\"}",
     "legendFormat": "flushes"
    }
   ]
  },
  {
   "title": "Inode Cluster Flushes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "xfs.perdev.icluster_flushcnt{hostname == \"$host\"}",
     "legendFormat": "count"
    },
    {
     "expr": "xfs.perdev.icluster_flushinode{hostname == \"$host\"}",
     "legendFormat": "inodes"
    }
   ]
  }
 ]
}