{
 "title": "Swift DB info",
 "tags": [ "swift" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-redis-datasource" },
   { "name": "host", "query": "label_values(hostname)" },
   { "name": "instance", "query": "label_values(swift_db_name)" }
  ]
 },
 "panels": [
  { "title": "Swift DB info For $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Number of Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "swiftdbinfo.object.count{hostname == \"$host\", swift_db_name == \"$instance\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Size of DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "swiftdbinfo.size{hostname == \"$host\", swift_db_name == \"$instance\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Distrbution of object sizes in DB",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "swiftdbinfo.object.dist{hostname == \"$host\", swift_db_name == \"$instance\"}",
     "legendFormat": "$instance"
    }
   ]
  }
 ]
}