apiVersion: v1
kind: Service
metadata:
  name: keystone-svc
  namespace: {{ include "swiftacular.namespace" . }}
  labels:
    app: keystone
    {{- include "swiftacular.labels" . | nindent 4 }}
spec:
  selector:
    app: keystone
  ports:
    - name: public
      port: 5000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: keystone-nodeport
  namespace: {{ include "swiftacular.namespace" . }}
  labels:
    app: keystone
    {{- include "swiftacular.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: keystone
  ports:
    - name: public
      port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
