---
#
# Run a basic test to see if keystone is running
#

- name: Test keystone service with openstack CLI
  ansible.builtin.command: /usr/bin/openstack user list
  environment:
    OS_TOKEN: "{{ keystone_admin_token }}"
    OS_URL: "https://{{ keystone_server }}:35357/v2.0"
    OS_IDENTITY_API_VERSION: "2.0"
  register: keystone_test
  failed_when: keystone_test.rc != 0
  changed_when: false
  retries: 3
  delay: 5
