---
- name: Install required keystone packages
  ansible.builtin.apt:
    pkg: "{{"
    state: installed
    update_cache: "yes"
    cache_valid_time: "3600"
    cmd: item }}
  with_items: authentication_ubuntu_packages

- name: Create empty /var/log/keystone/keystone.log
  ansible.builtin.command:
    creates: /var/log/keystone/keystone.log
    cmd: touch /var/log/keystone/keystone.log
- name: Ensure /var/log/keystone/keystone.log has the correct privileges
  ansible.builtin.file:
    path: /var/log/keystone/keystone.log
    owner: keystone
    group: keystone
- name: Remove default keystone sqlite database file
  ansible.builtin.file:
    path: /var/lib/keystone/keystone.db
    state: absent
