---
#
# Install and configure a keystone authentication server
#

- name: Play debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Play redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

#
# Common
#

- name: Play common.yml
  ansible.builtin.include_tasks: common.yml

- name: Play debian_test.yml
  ansible.builtin.include_tasks: debian_test.yml
  when: ansible_os_family == 'Debian'

- name: Play redhat_test.yml
  ansible.builtin.include_tasks: redhat_test.yml
  when: ansible_os_family == 'RedHat'
