---
#
# Run a basic test to see if keystone is running
#

- name: Test keystone with user list
  ansible.builtin.command: /usr/bin/openstack user list
  environment: "{{ admin_env }}"
  when: keystone_db_created.changed
  register: keystone_test
  failed_when: keystone_test.rc != 0
  changed_when: false
