---
- name: Install development tools and Python packages
  ansible.builtin.dnf:
    name:
      - gcc
      - python3-devel
      - python3-PyMySQL
    state: present
  become: true

- name: Install dnf-plugins-core for repository management
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  become: true

- name: Enable CRB (CodeReady Builder) repository
  ansible.builtin.command:
    cmd: dnf config-manager --enable crb
  become: true
  changed_when: true

- name: Install OpenStack Epoxy release package
  ansible.builtin.dnf:
    name: centos-release-openstack-epoxy
    state: present
  become: true

- name: Update all packages excluding problematic dependencies
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

  become: true

- name: Install MariaDB server and development packages
  ansible.builtin.dnf:
    name:
      - mariadb-server
      - mariadb-devel
    state: present
  become: true

- name: Install OpenStack Swift and core dependencies
  ansible.builtin.dnf:
    name:
      - openstack-swift
      - rsync
    state: present
  become: true

- name: Start and enable MariaDB service
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Create keystone directories # Test
  ansible.builtin.command: mkdir -p /etc/keystone /var/log/keystone
- name: Copy over /etc/keystone/logging.conf
  ansible.builtin.copy:
    src: redhat_logging.conf
    dest: /etc/keystone/logging.conf
    mode: "0640"
  notify: Restart keystone

- name: Create empty /var/log/keystone/error.log and access.log
  ansible.builtin.command:
    creates: /var/log/keystone/{{
    cmd: touch /var/log/keystone/{{ item }}.log item }}.log
  with_items:
    - error
    - access

- name: Ensure error.log and access.log are writable by keystone
  ansible.builtin.file:
    path: /var/log/keystone/{{
    state: file
    cmd: item }}.log
  with_items:
    - error
    - access

- name: Ensure keystone can write to /var/log/keystone
  ansible.builtin.file:
    path: /var/log/keystone
    recurse: "yes"
  notify: Restart keystone
