---
- name: Install python3-libselinux on all hosts
  hosts:
    - all
  gather_facts: true
  tasks:
    - name: Install python3-libselinux
      ansible.builtin.dnf:
        name: python3-libselinux
        state: present

# Setup a package_cache, especially when using
# your laptop and Vagrant
#
- name: Configure SELinux for Swift
  hosts: all
  tasks:
    - name: Let us port bind
      ansible.builtin.command: setsebool -P swift_can_network 1

- name: Setup package cache
  hosts: package_cache
  roles:
    - package_cache

- name: Apply common configuration
  hosts:
    - all
  roles:
    - common

- name: Redirect ansible network interface names
  hosts: all
  tasks:
    - name: Redirection ansible_ethN
      ansible.builtin.set_fact:
        ansible_eth1: "{{ ansible_ens6 }}"
        ansible_eth2: "{{ ansible_ens7 }}"
        ansible_eth3: "{{ ansible_ens8 }}"
        ansible_eth4: "{{ ansible_ens9 }}"

# - name: Configure SSL load balancer
#   hosts:
#   - lbssl
#   roles:
#   - lbssl

- name: Configure Swift common components
  hosts:
    - proxy
    - storage
    - package_cache
  roles:
    - swift_common

- name: Redirect ansible network interface names (second time)
  hosts: all
  tasks:
    - name: Redirection ansible_ethN twice
      ansible.builtin.set_fact:
        ansible_eth1: "{{ ansible_ens6 }}"
        ansible_eth2: "{{ ansible_ens7 }}"
        ansible_eth3: "{{ ansible_ens8 }}"
        ansible_eth4: "{{ ansible_ens9 }}"

- name: Configure Swift client
  hosts:
    - swiftclient
  roles:
    - swiftclient

- name: Configure authentication
  hosts:
    - authentication
  roles:
    - authentication

- name: Configure proxy servers
  hosts:
    - proxy
  roles:
    - proxy

#
# I would have expected serial to work here, and
# to be the right way to do it but at the time I
# tried received "too many files open" errors.
#
- name: Redirect ansible network interface names (third time)
  hosts: all
  tasks:
    - name: Redirection ansible_ethN again
      ansible.builtin.set_fact:
        ansible_eth1: "{{ ansible_ens6 }}"
        ansible_eth2: "{{ ansible_ens7 }}"
        ansible_eth3: "{{ ansible_ens8 }}"
        ansible_eth4: "{{ ansible_ens9 }}"

- name: Configure storage servers
  hosts:
    - storage
  serial: 1
  roles:
    - storage

#
# These are not so much roles as starting services
# though also includes distributing the ring files.
#

- name: Start proxy services
  hosts:
    - proxy
  #  vars_file:
  #  - include_tasks: vars/{{ansible_os_family}}.yml
  tasks:
    - name: Include proxy startup tasks
      ansible.builtin.include_tasks: start_proxy.yml

- name: Start storage services
  hosts:
    - storage
  #  vars_file:
  #  - include_tasks: vars/{{ansible_os_family}}.yml
  tasks:
    - name: Include storage startup tasks
      ansible.builtin.include_tasks: start_storage.yml

- name: Restore SELinux enforcement
  hosts:
    - all
  tasks:
    - name: Restore selinux state
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

#
# Probably best to run these on their own?
#

# -  name: Run tests
#    include_tasks: tests/tests.yml
