---
- name: Install jsonnet and jb (Jsonnet Bundler) from source for a regular user
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    jb_version: "v0.6.0"
  tasks:
    - name: Ensure ~/.local/bin directory exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Clone jsonnet repository from GitHub into user's home directory
      ansible.builtin.git:
        repo: "https://github.com/google/jsonnet.git"
        dest: "{{ lookup('env', 'HOME') }}/jsonnet"
        update: yes

    - name: Build jsonnet using make (non-root user)
      community.general.make:
        chdir: "{{ lookup('env', 'HOME') }}/jsonnet"

    - name: Add jsonnet to the user's local bin directory
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/jsonnet/jsonnet"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/jsonnet"
        mode: '0755'

    - name: Download and install jb (Jsonnet Bundler)
      ansible.builtin.get_url:
        url: "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/{{ jb_version }}/jb-linux-amd64"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/jb"
        mode: '0755'

    - name: Ensure ~/.local/bin is in the user's PATH
      ansible.builtin.blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        block: |
          export PATH="{{ lookup('env', 'HOME') }}/.local/bin:$PATH"
        state: present

    - name: Install jsonnet packages from jsonnetfile.json
      ansible.builtin.command:
        cmd: jb install
      environment:
        PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ lookup('env', 'PATH') }}"
      args:
        chdir: "{{ lookup('env', 'PWD') }}"
