---
# Apply patch to sharder.py to ensure sharding is always set to true.
# Then run workloader and verification.

- name: Sharder patch
  hosts: storage
  become: true
  tasks:
    - name: Copy the sharder patch file to the target host
      ansible.builtin.copy:
        src: sharder.patch
        dest: /tmp/sharder.patch

    - name: Install patch package
      ansible.builtin.command: dnf install -y patch
    - name: Check if sharder patch is already applied
      ansible.builtin.shell: patch --dry-run -p0 < /tmp/sharder.patch
      args:
        chdir: /usr/lib/python3.9/site-packages/swift/container
      register: patch_check
      failed_when: false
      changed_when: false

    - name: Apply sharder patch
      ansible.builtin.shell: patch -p0 < /tmp/sharder.patch
      args:
        chdir: /usr/lib/python3.9/site-packages/swift/container
      when: patch_check.rc == 0

    - name: Stop sharders
      ansible.builtin.command: swift-init container-sharder stop
      ignore_errors: true

    - name: Start sharders
      ansible.builtin.command: sudo swift-init container-sharder start
- name: Workload tests
  hosts: package_cache
  tasks:
    - name: Copy tests directory to package_cache host
      ansible.builtin.copy:
        src: workload_tests
        dest: /home/vagrant/

    - name: Install pytest using system package manager
      ansible.builtin.dnf:
        name: python3-pytest
        state: present

    - name: Install python3-swiftclient
      ansible.builtin.dnf:
        name: python3-swiftclient
        state: present

    # We're currently only running the tiny test. It would be good to run everything!
    - name: Run workload tests
      ansible.builtin.command: /usr/bin/python -m pytest test_workload.py::test_tiny_workload -svx
      args:
        chdir: /home/vagrant/workload_tests
      register: pytest_result

- name: Verify sharding
  hosts: storage
  tasks:
    # It's entirely possible that for bigger tests, it would take much longer than 10 minutes for sharding to complete.
    - name: Wait for sharding
      ansible.builtin.command: sleep 600
    - name: Get container sharding results
      ansible.builtin.shell: |  # Big ugly command to check whether container is sharded.
        for FILE in /srv/node/td*/containers/*/*/*/*.db; do swift-manage-shard-ranges $FILE info; done 2>&1 | grep '^Loaded.*the-test-container$' -A 20 | grep -m 1 "db_state" | sed -e "s/^db_state = //"
      register: command_output

    - name: Show output
      ansible.builtin.debug:
        var: command_output.stdout

    - name: Check the output
      ansible.builtin.fail:
        msg: "The container is unsharded"
      when: command_output.stdout == "unsharded"

    - name: Check if sharded # Also succeeds if output is empty result, meaning no replica on host
      ansible.builtin.command: sleep 0
      retries: 1
      delay: 0
      until: command_output.stdout == "sharded" or command_output.stdout == ""
      when: command_output.stdout != "sharded"
