---
- name: Put the *.ring.gz files on all storage servers
  ansible.builtin.copy:
    src: "fetch/{{ item }}.ring.gz"
    dest: "/etc/swift/{{ item }}.ring.gz"
    owner: swift
    group: swift
    mode: "0640"
  register: new_rings
  with_items:
    - account
    - object
    - container

- name: Make sure default configuration files are *not* there
  ansible.builtin.file:
    state: absent
    path: /etc/swift/{{ item }}-server.conf
  with_items:
    - account
    - object
    - container

- name: Restart swift services when rings changed
  when: new_rings.changed
  block:
    - name: Stop swift-storage node services
      ansible.builtin.command: swift-init all stop
      register: swift_stop_result
      changed_when: swift_stop_result.rc == 0
      failed_when: false
      become: true

    - name: Restart swift-storage node services # noqa no-handler no-changed-when
      ansible.builtin.command: swift-init all start

    - name: Restart syslog # noqa no-handler no-changed-when
      ansible.builtin.service:
        name: rsyslog
        state: restarted
