---
#
# Create files necessary to start the proxy and also start it
#

- name: Rebalance rings
  ansible.builtin.command: swift-ring-builder {{ item }}.builder rebalance creates=/etc/swift/{{ item }}.ring.gz chdir=/etc/swift
  register: rebalance
  with_items:
    - account
    - object
    - container

# This will fetch from all proxies, if there are more than one and put the rings files in the same spot, which is Ok but not perfect
- name: Grab resulting *.ring.gz files and put them on all proxy and storage nodes
  ansible.builtin.fetch: dest=fetch/{{ item }}.ring.gz flat=yes src=/etc/swift/{{ item }}.ring.gz
  when: rebalance.changed
  with_items:
    - account
    - object
    - container

- name: Start swift-proxy on proxy nodes
  ansible.builtin.service: name=swift-proxy state=started
  when: ansible_os_family == 'Debian'

- name: Start swift-proxy on proxy nodes
  ansible.builtin.service: name=openstack-swift-proxy state=started
  when: ansible_os_family == 'RedHat'

- name: Check if object-expirer is running
  ansible.builtin.command: swift-init object-expirer status
  register: expirer_status
  failed_when: false
  changed_when: false

- name: Start object-expirer on proxy nodes
  ansible.builtin.command: swift-init object-expirer start
  when: expirer_status.rc != 0
