---
#
# Create files necessary to start the proxy and also start it
#

- name: Rebalance rings
  ansible.builtin.command:
    chdir: /etc/swift
    cmd: swift-ring-builder {{ item }}.builder rebalance
    creates: /etc/swift/{{ item }}.ring.gz
  register: rebalance
  with_items:
    - account
    - object
    - container
# noqa no-handler

# This will fetch from all proxies, if there are more than one and put the rings files in the same spot, which is Ok but not perfect
- name: Grab resulting *.ring.gz files and put them on all proxy and storage nodes # noqa no-handler
  ansible.builtin.fetch:
    src: /etc/swift/{{ item }}.ring.gz
    dest: fetch/{{ item }}.ring.gz
    flat: "yes"
  when: rebalance.changed
  with_items:
    - account
    - object
    - container

- name: Start swift-proxy on proxy nodes (Debian)
  ansible.builtin.service:
    name: swift-proxy
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'

- name: Start swift-proxy on proxy nodes (RedHat)
  ansible.builtin.service:
    name: openstack-swift-proxy
    state: started
    enabled: true
  when: ansible_os_family == 'RedHat'

- name: Check if object-expirer is running
  ansible.builtin.command: swift-init object-expirer status
  register: expirer_status
  failed_when: false
  changed_when: false

- name: Start object-expirer on proxy nodes # noqa no-changed-when
  ansible.builtin.command: swift-init object-expirer start
  when: expirer_status.rc != 0
  changed_when: expirer_status.rc != 0
