---
#
# Debian
#

- name: Debian specific tasks in swift_common.yaml
  ansible.builtin.include_tasks:
    file: debian.yml
    apply:
      tags: [packages, configure]
  when: ansible_os_family == 'Debian'
  tags: [always]

#
# Redhat
#

- name: RedHat specific tasks in swift_common.yaml
  ansible.builtin.include_tasks:
    file: redhat.yml
    apply:
      tags: [packages, configure]
  when: ansible_os_family == 'RedHat'
  tags: [always]

- name: Common tasks in swift_common.yaml
  ansible.builtin.include_tasks:
    file: common.yml
    apply:
      tags: [packages, configure]
  tags: [always]
