---

- name: install required packages for swift_common
  shell: |
    dnf update -y
    dnf config-manager --enable crb
    dnf install -y centos-release-openstack-epoxy
    # setenforce 0
    dnf update -y
    dnf install -y openstack-swift rsync