---
- name: Copy over testrc file
  ansible.builtin.template:
    src: testrc.j2
    dest: "/home/{{ ansible_env.SUDO_USER }}/testrc"

- name: Copy over adminrc file
  ansible.builtin.template:
    src: adminrc.j2
    dest: "/home/{{ ansible_env.SUDO_USER }}/adminrc"
