---
- name: Copy over testrc file
  #  template: src=testrc.j2 dest=/home/{{ ansible_env.SUDO_USER }}/testrc
  ansible.builtin.template:
    src: testrc.j2
    dest: /{{
    cmd: ansible_env.SUDO_USER }}/testrc
- name: Copy over adminrc file
  #  template: src=adminrc.j2 dest=/home/{{ ansible_env.SUDO_USER }}/adminrc
  ansible.builtin.template:
    src: adminrc.j2
    dest: /{{
    cmd: ansible_env.SUDO_USER }}/adminrc
