---
- name: Start and enable memcached
  ansible.builtin.systemd:
    name: memcached
    state: started
    enabled: true

- name: Ensure permissions on /var/cache/swift
  ansible.builtin.file:
    path: /var/cache/swift
    state: directory
    group: swift
    owner: swift
    mode: "0700"

- name: Copy over proxy-server.conf
  ansible.builtin.template:
    src: proxy-server.conf.j2
    dest: /etc/swift/proxy-server.conf
    owner: swift
    group: swift
    mode: "0640"

- name: Copy over object-expirer.conf
  ansible.builtin.template:
    src: object-expirer.conf.j2
    dest: /etc/swift/object-expirer.conf
    owner: swift
    group: swift
    mode: "0640"

- name: Run swift-ring-builder for accounts, containers, and objects
  ansible.builtin.command:
    chdir: /etc/swift
    creates: /etc/swift/{{ item }}.ring.gz
    cmd: swift-ring-builder {{ item }}.builder create {{ partition_power }} {{ replicas }} {{ min_part_hours }}
  with_items:
    - account
    - container
    - object
