---

authentication_redhat_packages:
  - openstack-keystone

authentication_ubuntu_packages:
  - keystone
  - python-keyring
  - mariadb-server
  - python3-pymysql

authentication_admin_env:
  OS_USERNAME: admin
  OS_PASSWORD: "{{ keystone_admin_token }}"
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_DOMAIN_NAME: Default
  OS_AUTH_URL: http://{{ keystone_server }}:5000/v3
  OS_IDENTITY_API_VERSION: 3
