---

proxy_ubuntu_packages:
  - swift-proxy
  - swift-object
  - memcached
  - python-keystoneclient
  - python-swiftclient
  - swift-plugin-s3
  - python-netifaces
  - python-xattr
  - python-memcache

proxy_redhat_packages:
  - openstack-swift-proxy
  - memcached
  - libevent
  - libevent-devel
