---
- name: Install required package_cache packages
  ansible.builtin.apt:
    pkg: "{{"
    state: installed
    update_cache: "yes"
    cache_valid_time: "3600"
    cmd: item }}
  with_items:
    - apt-cacher-ng
