---

#
# Debian
#

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

#
# Redhat
#

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
