---
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]

#
# Debian
#

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

#
# Redhat
#

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
