---
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
  tags: [always]

#
# Debian
#

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks:
    file: debian.yml
    apply:
      tags: [packages, configure]
  when: ansible_os_family == 'Debian'
  tags: [always]

#
# Redhat
#

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks:
    file: redhat.yml
    apply:
      tags: [packages, configure]
  when: ansible_os_family == 'RedHat'
  tags: [always]
