---

- name: install squid to cache rpm packages
  command: yum install -y squid

- name: install pip
  command: yum install -y python3-pip

- name: install pytest
  command: pip3 install pytest

#- name: install python2-pip
#  command: yum install -y python2-pip

#- name: install selinux
#  command: pip2 install selinux

