---
- name: Install squid to cache rpm packages
  ansible.builtin.dnf:
    name: squid
    state: present
  become: true

- name: Install pytest using system package manager
  ansible.builtin.dnf:
    name: python3-pytest
    state: present
