---

- name: Install squid to cache rpm packages
  dnf:
    name: squid
    state: present
  become: yes

- name: Install pytest using system package manager
  ansible.builtin.dnf:
    name: python3-pytest
    state: present
