---

- name: Install squid to cache rpm packages
  dnf:
    name: squid
    state: present
  become: yes

- name: Install pip
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install pytest
  pip:
    name: pytest
    state: present
