---
- name: Install package cache components
  ansible.builtin.include_tasks: redhat_install.yml

- name: Configure package cache
  ansible.builtin.include_tasks: redhat_configure.yml

- name: Manage package cache service
  ansible.builtin.include_tasks: redhat_service.yml
