---
#
# Create an SSL certificate for pound to use
#

- name: Create self-signed SSL cert for pound
  ansible.builtin.command:
    cmd: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ ansible_ens6.ipv4.address }}" -days 3650 -keyout /etc/pound/server.key -out
      /etc/pound/server.crt -extensions v3_ca
    creates: /etc/pound/server.crt
  notify:
    - Verify ssl cert
    - Create combined pem file
    - Restart pound
    - Read certificate file
    - Read private key file
