apiVersion: v1
kind: Secret
metadata:
  name: swift-secrets
  namespace: {{ include "swiftacular.namespace" . }}
  labels:
    {{- include "swiftacular.labels" . | nindent 4 }}
type: Opaque
stringData:
  keystoneAdminPassword: {{ .Values.secrets.keystoneAdminPassword | quote }}
  keystoneMysqlPassword: {{ .Values.secrets.keystoneMysqlPassword | quote }}
  keystoneGenericServicePassword: {{ .Values.secrets.keystoneGenericServicePassword | quote }}
  keystoneTestUserPassword: {{ .Values.secrets.keystoneTestUserPassword | quote }}
  {{- if .Values.grafana.enabled }}
  grafanaAdminPassword: {{ .Values.secrets.grafanaAdminPassword | quote }}
  {{- end }}
