---
#
# NTP
#

- name: Install ntp package
  ansible.builtin.apt:
    name: ntp
    state: present

- name: Set timezone file
  ansible.builtin.template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
  register: timezone
  notify:
    - Stop ntpd
    - Sync time with NTP server
    - Start ntpd
    - Apply system timezone
