---
- name: Install precise openstack havana apt repository
  ansible.builtin.apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/havana main' state=present
  register: new_repo
  when: ansible_distribution_release == "precise"

- name: Update apt
  ansible.builtin.command: apt-get update
  when: new_repo.changed
