---
#
# Stop portmapper
# 

- name: Ensure portmap is not running
  ansible.builtin.service:
    name: portmap
    state: stopped
    enabled: "no"
  ignore_errors: true

#
# NTP
# 

- ansible.builtin.include_tasks: debian_ntp.yml
- ansible.builtin.include_tasks: debian_package_cache.yml
- ansible.builtin.include_tasks: debian_openstack_repository.yml
