---

- name: Install Swift dependencies
  dnf:
    name:
      - python3-devel
      - gcc
    state: present
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Install OpenStack repository
  dnf:
    name: centos-release-openstack-epoxy
    state: present
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Install OpenStack SELinux package
  dnf:
    name: openstack-selinux
    state: present
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Enable CodeReady Builder repository
  command: dnf config-manager --set-enabled crb
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Install OpenStack client
  dnf:
    name: python3-openstackclient
    state: present
  become: yes
  when: ansible_distribution == 'CentOS'
