---

- name: Install python3-pip
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install SELinux Python bindings
  dnf:
    name: python3-libselinux
    state: present
  become: yes