---
- name: Install Swift dependencies
  ansible.builtin.dnf:
    name:
      - python3-devel
      - gcc
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install OpenStack repository
  ansible.builtin.dnf:
    name: centos-release-openstack-epoxy
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install OpenStack SELinux package
  ansible.builtin.dnf:
    name: openstack-selinux
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Enable CodeReady Builder repository
  ansible.builtin.dnf:
    name: []  # Don't install/update any packages
    enablerepo: crb
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install OpenStack client
  ansible.builtin.dnf:
    name: python3-openstackclient
    state: present
  become: true
  when: ansible_distribution == 'CentOS'
