---
- name: Make sure /srv/node exists
  ansible.builtin.file:
    path: /srv/node
    state: directory
    owner: swift
    group: swift
    mode: "0755"

- name: Make sure /var/swift/recon exists
  ansible.builtin.file:
    path: /var/swift/recon
    state: directory
    owner: swift
    group: swift
    mode: "0750"

- name: Make /srv/node disk device directories
  ansible.builtin.file:
    state: directory
    path: /srv/node/{{ disk_prefix }}{{ item | int - 1 }}
    owner: swift
    group: swift
    mode: "0770"
  with_sequence: count={{ disks }}
#  when: "losetup.rc > 0"

# NOTE: Would likely not want the nobootwait in production, but in virtualbox the loop devices won't
#       be setup yet so it won't be able to reboot without that setting, assuming the mount points
#       are setup in /etc/fstab
# NOTE: later on removed nobootwait b/c didn't work on redhat
# - name: mount swift disks
#   mount: name=/srv/node/{{ disk_prefix }}{{ item }} state=mounted src=/dev/loop{{ item }} opts="noatime,nodiratime,nobarrier" fstype=xfs
#   with_sequence: count={{ disks }}
#   when: "losetup.rc > 0"
#   tags:
#     - remount_loop_devices

- name: Create disk files
  ansible.builtin.command: truncate -s 1GB /srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}
  with_sequence: count={{ disks }}
  args:
    creates: /srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}

- name: Format disks with XFS
  community.general.filesystem:
    fstype: xfs
    dev: "/srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}"
    force: false
  with_sequence: count={{ disks }}

# - name: format nvme disks
#   shell: mkfs.xfs -f /dev/nvme{{ item|int - 1 }}n1;
#   with_sequence: count={{ disks }}
#   ignore_errors: True

- name: Add mount to /etc/fstab
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "/srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }} /srv/node/{{ disk_prefix }}{{ item | int - 1 }} xfs loop,noatime 0 0"
  with_sequence: count={{ disks }}

# - name: Get the mount
#   ansible.builtin.command: mount -a
# - name: Set permissions on /srv/node/* after being mounted
#   ansible.builtin.file:
#     state: directory
#     path: /srv/node/{{
#     owner: swiftroles/storage/tasks/common.yml
#     group: swift
#     mode: "0770"
#     cmd: disk_prefix }}{{ item | int - 1 }}
#   with_sequence: count={{ disks }}

- name: Mount all filesystems from fstab
  ansible.posix.mount:
    src: "{{ item.device }}"
    path: "{{ item.mount }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  with_items: "{{ ansible_mounts }}"
  when: item.mount.startswith('/srv/node/')

#
# Configure rsync
#

- name: Install rsync
  ansible.builtin.dnf:
    name: rsync-daemon
    state: present
  become: true

- name: Copy over rsyncd.conf to swift storage
  ansible.builtin.template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
  become: true

- name: Make sure rsync daemon is running
  ansible.builtin.service:
    name: rsyncd
    state: started
    enabled: true

- name: Ensure *-server directories exist in /etc/swift
  ansible.builtin.file:
    path: "/etc/swift/{{ item }}-server"
    state: directory
    mode: "0755"
  with_items:
    - account
    - container
    - object
  become: true

- name: Copy over *-server.conf files
  ansible.builtin.template:
    src: "{{ item }}-server.conf.j2"
    dest: "/etc/swift/{{ item }}-server/{{ item }}-server.conf"
  with_items:
    - account
    - container
    - object
  become: true

- name: Copy over *-replication.conf files
  ansible.builtin.template:
    src: "{{ item }}-replication.conf.j2"
    dest: "/etc/swift/{{ item }}-server/{{ item }}-replication.conf"
  with_items:
    - account
    - container
    - object
  become: true
