---
- name: Make sure /srv/node exists
  ansible.builtin.file:
    path: /srv/node
    state: directory
    owner: swift
    group: swift
    mode: "0755"

- name: Make sure /var/swift/recon exists
  ansible.builtin.file:
    path: /var/swift/recon
    state: directory
    owner: swift
    group: swift
    mode: "0750"

- name: Make /srv/node disk device directories
  ansible.builtin.file:
    state: directory
    path: /srv/node/{{ disk_prefix }}{{ item | int - 1 }}
    owner: swift
    group: swift
    mode: "0770"
  with_sequence: count={{ disks }}

- name: Create disk files
  ansible.builtin.command: truncate -s 1GB /srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}
  with_sequence: count={{ disks }}
  args:
    creates: /srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}

- name: Format disks with XFS
  community.general.filesystem:
    fstype: xfs
    dev: "/srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}"
    force: false
  with_sequence: count={{ disks }}

- name: Add mount to /etc/fstab
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "/srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }} /srv/node/{{ disk_prefix }}{{ item | int - 1 }} xfs loop,noatime 0 0"
  with_sequence: count={{ disks }}

- name: Mount swift storage devices
  ansible.posix.mount:
    src: "/srv/node/disk-{{ disk_prefix }}{{ item | int - 1 }}"
    path: "/srv/node/{{ disk_prefix }}{{ item | int - 1 }}"
    fstype: xfs
    opts: loop,noatime
    state: mounted
  with_sequence: count={{ disks }}

- name: Set permissions on mounted storage devices
  ansible.builtin.file:
    state: directory
    path: "/srv/node/{{ disk_prefix }}{{ item | int - 1 }}"
    owner: swift
    group: swift
    mode: "0770"
  with_sequence: count={{ disks }}

#
# Configure rsync
#

- name: Install rsync
  ansible.builtin.dnf:
    name: rsync-daemon
    state: present
  become: true

- name: Copy over rsyncd.conf to swift storage
  ansible.builtin.template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
  become: true

- name: Make sure rsync daemon is running
  ansible.builtin.service:
    name: rsyncd
    state: started
    enabled: true

- name: Ensure *-server directories exist in /etc/swift
  ansible.builtin.file:
    path: "/etc/swift/{{ item }}-server"
    state: directory
    mode: "0755"
  with_items:
    - account
    - container
    - object
  become: true

- name: Copy over *-server.conf files
  ansible.builtin.template:
    src: "{{ item }}-server.conf.j2"
    dest: "/etc/swift/{{ item }}-server/{{ item }}-server.conf"
  with_items:
    - account
    - container
    - object
  become: true

- name: Copy over *-replication.conf files
  ansible.builtin.template:
    src: "{{ item }}-replication.conf.j2"
    dest: "/etc/swift/{{ item }}-server/{{ item }}-replication.conf"
  with_items:
    - account
    - container
    - object
  become: true
