---

#
# Debian
#

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

#
# Redhat
#

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: common.yml
- include_tasks: common_build_rings.yml
