---
# Configure swift storage

# Package installation
- name: Install storage packages
  ansible.builtin.dnf:
    name: "{{ storage_redhat_packages }}"
    state: present
  tags: [packages]

# Configuration tasks
- name: Copy rsync init script to /etc/init.d/rsync
  ansible.builtin.copy:
    src: redhat_rsync.init
    dest: /etc/rc.d/init.d/rsync
    owner: root
    group: root
    mode: "0755"
  tags: [configure]
