---
- name: Cleanup authentication database
  hosts: authentication
  tasks:
  # works for both MySQL and MariaDB
    - name: Remove keystone mysql/mariadb database
      community.mysql.mysql_db:
        name: keystone
        state: absent
