---
- name: Cleanup storage disk images and mounts
  hosts: storage
  tasks:
    - name: Unmount disk directories
      ansible.builtin.command: umount /srv/node/{{ disk_prefix }}{{ item }}
      with_sequence: count=3
      failed_when: false

    - name: Detach loop devices
      ansible.builtin.command: losetup -d /dev/loop{{ item }}
      with_sequence: count=3
      failed_when: false

    - name: Remove disk image files
      ansible.builtin.file:
        path: /var/tmp/{{ disk_prefix }}{{ item }}.img
        state: absent
      with_sequence: count=3
