---
- hosts: storage

  tasks:
    - name: Cleanup image mounts
      ansible.builtin.shell: umount /srv/node/{{ disk_prefix }}{{ item }}; losetup -d /dev/loop{{ item }}; rm -f /var/tmp/{{ disk_prefix }}{{ item }}.img
      with_sequence: count=3
