---
- hosts: storage

  tasks:
    - name: Stop all swift-storage node services
      ansible.builtin.command: swift-init all stop
      ignore_errors: true

    - name: Cleanup image mounts
      ansible.builtin.shell: umount /srv/node/{{ disk_prefix }}{{ item }}; losetup -d /dev/loop{{ item }}; rm -f /var/tmp/{{ disk_prefix }}{{ item }}.img
      with_sequence: count=3

- hosts: proxy

  tasks:
    - name: Stop swift-proxy on proxy nodes
      ansible.builtin.service: name=openstack-swift-proxy state=stopped
      when: ansible_os_family == 'RedHat'

    - name: Stop swift-proxy on proxy nodes
      ansible.builtin.service: name=swift-proxy state=stopped
      when: ansible_os_family == 'Debian'

    - name: Remove builder files
      ansible.builtin.command: rm -f /etc/swift/{{item}}.builder
      with_items:
        - account
        - container
        - object

- hosts:
    - storage
    - proxy

  tasks:
    - name: Remove ring files
      ansible.builtin.command: rm -f /etc/swift/{{item}}.ring.gz
      with_items:
        - account
        - container
        - object
